CREATE TABLE IF NOT EXISTS PUBLIC."user" (
	id BIGINT NOT NULL AUTO_INCREMENT,
	login varchar NOT NULL,
	name varchar NOT NULL,
	birthday DATE,
	email varchar NOT NULL,
	CONSTRAINT user_pk PRIMARY KEY (ID),
	CONSTRAINT user_unique UNIQUE (LOGIN)
);


CREATE TABLE IF NOT EXISTS PUBLIC."mpa" (
	id BIGINT NOT NULL AUTO_INCREMENT,
	name varchar NOT NULL,
	CONSTRAINT MPA_PK PRIMARY KEY (ID)
);


CREATE TABLE IF NOT EXISTS PUBLIC."film" (
	id BIGINT NOT NULL AUTO_INCREMENT,
	name varchar NOT NULL,
	description varchar,
	release_date DATE NOT NULL,
	duration INTEGER,
	mpa_id INTEGER,
	CONSTRAINT film_pk PRIMARY KEY (ID),
	CONSTRAINT MPA_MPA_ID_FK FOREIGN KEY (mpa_id) REFERENCES PUBLIC."mpa"(ID)
);

CREATE TABLE IF NOT EXISTS PUBLIC."genre" (
	id BIGINT NOT NULL AUTO_INCREMENT,
	name varchar NOT NULL,
	CONSTRAINT GENRE_PK PRIMARY KEY (ID)
);


CREATE TABLE IF NOT EXISTS PUBLIC."user_friend" (
	user_id BIGINT NOT NULL,
	friend_id BIGINT NOT NULL,
	is_accepted BOOLEAN DEFAULT FALSE NOT NULL,
	CONSTRAINT USER_FRIEND_PK PRIMARY KEY (FRIEND_ID,USER_ID),
	CONSTRAINT USER_FRIEND_USER_FK_1 FOREIGN KEY (USER_ID) REFERENCES PUBLIC."user"(ID),
	CONSTRAINT USER_FRIEND_USER_FK_2 FOREIGN KEY (FRIEND_ID) REFERENCES PUBLIC."user"(ID)
);


CREATE TABLE IF NOT EXISTS PUBLIC."film_genre" (
	film_id BIGINT NOT NULL,
	genre_id BIGINT NOT NULL,
	CONSTRAINT FILM_GENRE_PK PRIMARY KEY (FILM_ID,GENRE_ID),
	CONSTRAINT FILM_GENRE_FILM_FK FOREIGN KEY (FILM_ID) REFERENCES PUBLIC."film"(ID),
	CONSTRAINT FILM_GENRE_GENRE_FK FOREIGN KEY (GENRE_ID) REFERENCES PUBLIC."genre"(ID)
);

CREATE TABLE IF NOT EXISTS PUBLIC."user_film_like" (
	film_id BIGINT NOT NULL,
	user_id BIGINT NOT NULL,
	CONSTRAINT USER_FILM_LIKE_PK PRIMARY KEY (FILM_ID,USER_ID),
	CONSTRAINT USER_FILM_LIKE_FILM_FK FOREIGN KEY (FILM_ID) REFERENCES PUBLIC."film"(ID),
	CONSTRAINT USER_FILM_LIKE_USER_FK FOREIGN KEY (USER_ID) REFERENCES PUBLIC."user"(ID)
);